name: LinuxRelease
on: [push, pull_request,repository_dispatch]
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-${{ github.head_ref || '' }}-${{ github.base_ref || '' }}-${{ github.ref != 'refs/heads/master' || github.sha }}
  cancel-in-progress: true

jobs:
 # Use duckdb's CI to deploy binaries to a custom
 linux-extensions-64:
    name: Linux Extensions (64 Bit)
    runs-on: ubuntu-latest
    container: ubuntu:16.04
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.S3_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.S3_KEY }}
      AWS_DEFAULT_REGION: us-east-1

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0

    # Todo we now do a lot of this shit twice
    - name: Install stuff
      shell: bash
      run: |
        apt-get update -y -qq
        apt-get install -y -qq software-properties-common
        add-apt-repository ppa:git-core/ppa
        apt-get update -y -qq
        apt-get install -y -qq ninja-build make gcc-multilib g++-multilib libssl-dev wget openjdk-8-jdk zip maven unixodbc-dev libc6-dev-i386 lib32readline6-dev libssl-dev libcurl4-gnutls-dev libexpat1-dev gettext unzip build-essential checkinstall libffi-dev curl libz-dev openssh-client

    - name: Install Git 2.18.5
      shell: bash
      run: |
        wget https://github.com/git/git/archive/refs/tags/v2.18.5.tar.gz
        tar xvf v2.18.5.tar.gz
        cd git-2.18.5
        make
        make prefix=/usr install
        git --version

    - name: Update DuckDB submodule
      run: |
        git config --global --add safe.directory '*'
        make pull

    - uses: ./duckdb/.github/actions/ubuntu_16_setup

    # Build extension
    - name: Deploy
      if: ${{ inputs.deploy_as != '' }}
      shell: bash
      run: |
        make release

    # Deploy binary # todo_replace bogus version when we have confirmed this will not bork production
    - name: Deploy
      if: ${{ inputs.deploy_as != '' }}
      shell: bash
      run: |
        cd  ${{ inputs.build_dir}}
        ./scripts/extension-upload.sh bogus_platform bogus_version ${{ secrets.S3_BUCKET }} 0

    - name: Test
      shell: bash
      env:
        AWS_ACCESS_KEY_ID: ${{ inputs.s3_id }}
        AWS_SECRET_ACCESS_KEY: ${{ inputs.s3_key }}
        AWS_DEFAULT_REGION: us-east-1
      run: |
        cd  ${{ inputs.build_dir}}
        if [[ "$GITHUB_REF" =~ ^(refs/heads/master|refs/tags/v.+)$ && "$GITHUB_REPOSITORY" = "duckdb/duckdb" ]] ; then
          ./scripts/extension-upload-test.sh
        else
          ./scripts/extension-upload-test.sh local
        fi

    - uses: ./.github/actions/build_extensions
      with:
        post_install: rm build/release/src/libduckdb*
        deploy_as: linux_amd64



    - uses: actions/upload-artifact@v2
      with:
        name: linux-extensions-64
        path: |
          build/release/extension/*/*.duckdb_extension