name: MacOS
on: [push, pull_request,repository_dispatch]
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-${{ github.head_ref || '' }}-${{ github.base_ref || '' }}-${{ github.ref != 'refs/heads/main' || github.sha }}
  cancel-in-progress: true

jobs:
  macos-extensions:
    name: OSX Extensions (Universal)
    runs-on: macos-latest
    env:
      OSX_BUILD_UNIVERSAL: 1
      GEN: ninja

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          submodules: 'true'

      - name: Install Ninja
        run: brew install ninja

      - uses: actions/setup-python@v2
        with:
          python-version: '3.7'

#         # Build extension
#      - name: Build extension
#        shell: bash
#        run: |
#          make release
#
#      # TODO: when adding S3 uploads, this can do remote tests
#      - name: Test
#        shell: bash
#        run: |
#          ./duckdb/scripts/extension-upload-test.sh local oote
#
#      - uses: actions/upload-artifact@v2
#        with:
#          name: macos-extensions-universal
#          path: |
#            build/release/extension/boilerplate/boilerplate.duckdb_extension

      # TODO also check if credentials are available for uploading
      - name: Deploy
        shell: bash
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.s3_id }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.s3_key }}
          AWS_DEFAULT_REGION: ${{ secrets.s3_region }}
          BUCKET_NAME: ${{ secrets.bucket }}
        run: |
          cd duckdb
          git fetch --tags
          export DUCKDB_VERSION=`git tag --points-at HEAD`
          echo $DUCKDB_VERSION
          export DUCKDB_VERSION=${DUCKDB_VERSION:=`git log -1 --format=%h`}
          echo $DUCKDB_VERSION
          cd ..
          if [[ "$GITHUB_REF" =~ ^(refs/tags/v.+)$ ]] ; then
            python -m pip install awscli
            ./scripts/extension-upload.sh boilerplate ${{ github.ref_name }} $DUCKDB_VERSION osx_amd64 $BUCKET_NAME
            ./scripts/extension-upload.sh boilerplate ${{ github.ref_name }} $DUCKDB_VERSION osx_arm64 $BUCKET_NAME
          elif [[ "$GITHUB_REF" =~ ^(refs/heads/main)$ ]] ; then
            python -m pip install awscli
            ./scripts/extension-upload.sh boilerplate `git log -1 --format=%h` $DUCKDB_VERSION osx_amd64 $BUCKET_NAME
            ./scripts/extension-upload.sh boilerplate `git log -1 --format=%h` $DUCKDB_VERSION osx_arm64 $BUCKET_NAME
          fi