#
# NOTE: if python tests are unused, deleting this file or disabling the workflow on GitHub will speed up CI
#

name: Python
on: [push, pull_request,repository_dispatch]
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-${{ github.head_ref || '' }}-${{ github.base_ref || '' }}-${{ github.ref != 'refs/heads/master' || github.sha }}
  cancel-in-progress: true

defaults:
  run:
    shell: bash

jobs:
  python:
    name: Python
    runs-on: macos-latest
    env:
      GEN: ninja

    steps:
      - name: Install Ninja
        run: brew install ninja

      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          submodules: 'true'

      - uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Build DuckDB (Python)
        run: make build_python_debug

      - name: Run Python client tests
        run: |
          (cd test/python && python -m pytest)