on: [push, pull_request,repository_dispatch]

defaults:
  run:
    shell: bash

jobs:
  sql:
    name: SQL
    runs-on: macos-latest
    env:
      GEN: ninja

    steps:
    - name: Install Ninja
      run: brew install ninja

    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Update DuckDB submodule
      run: |
        git config --global --add safe.directory '*'
        make pull

    - name: Build
      run: make release_bundled

    - name: Test
      run: make test_release