name: Windows
on: [push, pull_request,repository_dispatch]
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-${{ github.head_ref || '' }}-${{ github.base_ref || '' }}-${{ github.ref != 'refs/heads/main' || github.sha }}
  cancel-in-progress: true

jobs:
  win-extensions-64:
    name: Windows Extensions (x64)
    runs-on: windows-latest
    strategy:
      matrix:
        # empty string builds current submodule version, add commits/tags to build against other DuckDB versions
        duckdb_version: [ '' ]

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          submodules: 'true'

      - uses: actions/setup-python@v2
        with:
          python-version: '3.7'

      - name: Checkout DuckDB to version
        if: ${{ matrix.duckdb_version != ''}}
        shell: bash
        run: |
          cd duckdb
          git checkout ${{ matrix.duckdb_version }}

      - name: Build extension
        shell: bash
        run: |
          make release
          build/release/test/Release/unittest.exe

      - uses: actions/upload-artifact@v2
        with:
          name: linux-extensions-64-aarch64
          path: |
            build/release/extension/boilerplate/boilerplate.duckdb_extension

      - name: Deploy
        shell: bash
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.S3_DEPLOY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.S3_DEPLOY_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.S3_REGION }}
          BUCKET_NAME: ${{ secrets.S3_BUCKET }}
          TEST_VARIABLE: ${{ env.TEST_VARIABLE }}
        run: |
          cd duckdb
          git fetch --tags
          export DUCKDB_VERSION=`git tag --points-at HEAD`
          export DUCKDB_VERSION=${DUCKDB_VERSION:=`git log -1 --format=%h`}
          cd ..
          if [[ "$AWS_ACCESS_KEY_ID" == "" ]] ; then
            echo 'No key set, skipping'
          elif [[ "$GITHUB_REF" =~ ^(refs/tags/v.+)$ ]] ; then
            python -m pip install awscli
            ./scripts/extension-upload.sh boilerplate ${{ github.ref_name }} $DUCKDB_VERSION windows_amd64 $BUCKET_NAME
          elif [[ "$GITHUB_REF" =~ ^(refs/heads/main)$ ]] ; then
            python -m pip install awscli
            ./scripts/extension-upload.sh boilerplate `git log -1 --format=%h` $DUCKDB_VERSION windows_amd64 $BUCKET_NAME
          fi