name: Windows
on: [push, pull_request,repository_dispatch]
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-${{ github.head_ref || '' }}-${{ github.base_ref || '' }}-${{ github.ref != 'refs/heads/main' || github.sha }}
  cancel-in-progress: true

jobs:
  win-extensions-64:
    name: Windows Extensions (x64)
    runs-on: windows-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ inputs.s3_id }}
      AWS_SECRET_ACCESS_KEY: ${{ inputs.s3_key }}

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          submodules: 'true'

      - uses: actions/setup-python@v2
        with:
          python-version: '3.7'

#      - name: Build extension
#        shell: bash
#        env:
#          TREAT_WARNINGS_AS_ERRORS: 0
#        run: |
#          make release
#
#      # TODO: when adding  S3 uploads, this can do remote tests
#      - name: Test
#        shell: bash
#        run: |
#          ./duckdb/scripts/extension-upload-test.sh local oote
#
#      - uses: actions/upload-artifact@v2
#        with:
#          name: linux-extensions-64-aarch64
#          path: |
#            build/release/extension/boilerplate/boilerplate.duckdb_extension

      # TODO also check if credentials are available for uploading
      - name: Deploy
        shell: bash
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.s3_id }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.s3_key }}
          AWS_DEFAULT_REGION: ${{ secrets.s3_region }}
          BUCKET_NAME: ${{ secrets.bucket }}
        run: |
          mkdir -p build/release/extension/boilerplate
          touch build/release/extension/boilerplate/boilerplate.duckdb_extension
          cd duckdb
          git fetch --tags
          export DUCKDB_VERSION=`git tag --points-at HEAD`
          export DUCKDB_VERSION=${DUCKDB_VERSION:=`git log -1 --format=%h`}
          cd ..
          if [[ "$GITHUB_REF" =~ ^(refs/tags/v.+)$ ]] ; then
            python -m pip install awscli
            ./scripts/extension-upload.sh boilerplate ${{ github.ref_name }} $DUCKDB_VERSION windows_amd64 $BUCKET_NAME
          elif [[ "$GITHUB_REF" =~ ^(refs/heads/main)$ ]] ; then
            python -m pip install awscli
            ./scripts/extension-upload.sh boilerplate `git log -1 --format=%h` $DUCKDB_VERSION windows_amd64 $BUCKET_NAME
          fi